#!/bin/bash
echo -e a{a..z}"\n" b{a..z}"\n" c{a..z}"\n" d{a..z}"\n" e{a..z}"\n" f{a..z}"\n" g{a..z}"\n" h{a..z}"\n" i{a..z}"\n" j{a..z}"\n" k{a..z}"\n" l{a..z}"\n" m{a..z}"\n" n{a..z}"\n" o{{a..n},{p..z}}"\n" p{a..z}"\n" q{a..z}"\n" r{a..z}"\n" s{a..z}"\n" t{a..z}"\n" u{a..z}"\n" v{a..z}"\n" w{a..z}"\n" x{a..z}"\n" y{a..z}"\n" z{a..z} | sort -i

